### ISSUE TITLE
Link with traces is dead

### ISSUE THREAD

**Issue by 0xdeafbeef** [moka-rs/mokabench#15]
https://researcher.watson.ibm.com/researcher/view_person_subpage.php?id=4700 returns 404
Same with all trace files

**Comment by tatsuya6502** [comment]
Hi. Thanks for reporting! I put some of the trace files from the ARC paper in the following repository with [an author's permission](https://github.com/moka-rs/mokabench/issues/12#issuecomment-1681488659).

- https://github.com/moka-rs/cache-trace

I will do the followings in a day or so:

- Update the link in the [README](https://github.com/moka-rs/mokabench#download-the-trace-datasets) of mokabench to point to the above repository.
- Add other files from the ARC paper.

**Comment by tatsuya6502** [comment]
OK. I updated the link in the README of mokabench to point to the above repository.

- #16

And I also added other files from the ARC paper to the cache-trace repository:

- https://github.com/moka-rs/cache-trace/pull/2
